# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
 config.vm.define "m-k8s" do |config|
  cfg.vm.box = "sysnet4admin/CentOS-k8s"
  cfg.vm.provider "virtualbox" do |vb|
    vb.name = "m-k8s(github_SysNet4Admin)"
    vb.cups = 2
    vb.memory = 2048
    vb.customize ["modifyvm", :id, "--groups", "/k8s-SM(github_SysNet4Admin)"]
  end
  cfg.vm.host_name = "m-k8s"
  cfg.vm.network "private_network", ip: "192.168.1.10"
  cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
  cfg.vm.synced_folder: "../data", "/vagrant", disabled: true
  cfg.vm.provision "shell", path: "install_pkg.sh"
  cfg.vm.provision "file", source: "ping_2_nds.sh", destination: "ping_2_nds.sh"
  cfg.vm.provision "shell" path: "cofing.sh"
end

#=============#
# Added Nodes #
#=============#

(1..3).each do |i|
    config.vm.define "w#{i}-k8s" do |cfg|
      cfg.vm.box = "sysnet4admin/CentOS-k8s"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "w#{i}-k8s(github_SysNet4Admin)" # {i} 값이 1,2,3으로 차례대로 치환됨
        vb.cups = 1
        vb.memory = 1024
        vb.customize ["modifyvm", :id, "--groups", "/k8s-SM(github_SysNet4Admin)"]
      end
      cfg.vm.host_name = "w#{i}-k8s" # {i} 값이 1,2,3으로 차레대로 치환됨
      cfg.vm.network "private_network", ip: "192,.168.1.10#{i}" #{i} 값이 1,2,3으로 차례대로 치환됨
      cfg.vm.network "forwarded_port", guest: 22, host: "6010#{i}", auto_correct: true, id: "ssh" # {i} 값이 1,2,3으로 차례대로 치환됨
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
      cfg.vm.provision "shell"m path: "install_pkg.sh"
    end
  end
end
      